server:
  port: 8082

spring:
  profiles:
    active: dev

  data:
    mongodb:
      host: localhost
      port: 27017
      database: mongodb
      username: mongoadmin
      password: admin
      authentication-database: mongodb

      
  cloud:
    eureka:
      client:
        serviceUrl:
          defaultZone: http://localhost:8761/eureka/ 
          #defaultZone: http://host.docker.internal:8761/eureka/
        fetchRegistry: true 
        registerWithEureka: true  
        enabled: true

feign:
  client:
    config:
      credit-service:
        url: http://localhost:8084
      account-service:
        url: http://localhost:8081
      card-service:
        url: http://localhost:8087